name: hackathon2022-scale
channels:
  - conda-forge
  - defaults
dependencies:
  - pip==22.2.0
  - python==3.8

  - pip:
    - azure-cognitiveservices-speech==1.24.0
    - azure-identity==1.11.0
    - azure-keyvault-secrets==4.6.0
    - azure-storage-file-share==12.10.0
    - azure-storage-blob==12.14.0
    - ktrain==0.31.10
    - tensorflow==2.10.0
    - python-dotenv==0.21.0


